[package]
name    = "wormhole-core"
version = "0.1.0"
edition = "2018"

[lib]
name = "wormhole"


[profile.release]
opt-level = 3
lto       = "thin"


[dependencies]
borsh           = "*"
bstr            = "*"
byteorder       = "*"
hex             = "*"
hex-literal     = "*"
nom             = { version="7", default-features=false, features=["alloc"] }
primitive-types = { version="0.9.0", default-features=false }
sha3            = "0.9.1"


[dev-dependencies]
byteorder      = "*"
hex            = "*"
strum          = "*"
strum_macros   = "*"
